// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module sobel_top_sobel_core_linebuf1_RAM_2P_BRAM_1R1W (
    address1, ce1,
    d1, we1,
    q1,
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 11;
parameter AddressRange = 1920;

input [AddressWidth-1:0] address1;
input ce1;
input [DataWidth-1:0] d1;
input we1;
output reg [DataWidth-1:0] q1;
input reset;
input clk;

(* ram_style = "block" *) reg [DataWidth-1:0] ram[0:AddressRange-1];



// read first
always @(posedge clk)
begin
    if (ce1)
    begin
        if (we1)
            ram[address1] <= d1;
        q1 <= ram[address1];
    end
end


endmodule

